package com.vote.web;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.jufeng.database.DBManage;

/**
 * 初始化数据表的创建与数据的写入
 */
@WebServlet(urlPatterns = {"/install"},loadOnStartup=0)
public class InitServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public InitServlet() {
        super();
        Connection conn = DBManage.getConnection();
		Statement stmt;
		try {
			int ret = 0;
			stmt = conn.createStatement();
			ret = stmt.executeUpdate("CREATE MEMORY TABLE options(ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,LABEL VARCHAR(20))");
			System.out.println("create options " + ret);
			
			ret = stmt.executeUpdate("CREATE MEMORY TABLE votes(ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,result VARCHAR(20))");
			System.out.println("create votes " + ret);
			
			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('赞成')");
			System.out.println("insert " + ret);
			
			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('反对')");
			System.out.println("insert " + ret);
			
			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('弃权')");
			System.out.println("insert " + ret);
			
			stmt.close();
			System.out.println("stmt.close");
			DBManage.closeConnection(conn);
			System.out.println("conn.close");
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }


}
