package com.vote.web;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;

import com.jufeng.database.DBManage;

/**
 * 初始化数据表的创建与数据的写入
 */
@WebServlet(urlPatterns = {"/install"},loadOnStartup=0)
public class InitServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public InitServlet() {
        super();
        Connection conn = DBManage.getConnection();
		Statement stmt;
		try {
			int ret = 0;
			stmt = conn.createStatement();
			for (String sql : getInitSqlList()) {
				ret = stmt.executeUpdate(sql);
				System.out.println("["+ret+"]" + sql);
			}
//			ret = stmt.executeUpdate("CREATE MEMORY TABLE options(ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,LABEL VARCHAR(20))");
//			System.out.println("create options " + ret);
//			
//			ret = stmt.executeUpdate("CREATE MEMORY TABLE votes(ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,result VARCHAR(20))");
//			System.out.println("create votes " + ret);
//			
//			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('赞成')");
//			System.out.println("insert " + ret);
//			
//			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('反对')");
//			System.out.println("insert " + ret);
//			
//			ret = stmt.executeUpdate("INSERT INTO OPTIONS(LABEL) VALUES('弃权')");
//			System.out.println("insert " + ret);
			
			stmt.close();
			DBManage.closeConnection(conn);
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }

    
    public List<String> getInitSqlList(){
    	List<String> retList = new ArrayList<String>();
    	InputStream is = getClass().getResourceAsStream("/../init.sql");
    	
    	BufferedReader reader = new BufferedReader(new InputStreamReader(is));
    	String line;
    	try {
			while((line=reader.readLine()) != null){
				//System.out.println(line);
				if(line.length()>0 && !line.startsWith("#")){
					retList.add(line);
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
    	
    	return retList;
    }

}
